env:
  global:
    - CIBW_BEFORE_BUILD="yum install -y clang"
    - CIBW_TEST_REQUIRES="nose2"
    - CIBW_TEST_COMMAND="cd {project}/tests && nose2"
matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
install:
  # Python 3 is needed to run cibuildwheel 
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew install python3;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - pip3 install cibuildwheel
script:
  - cibuildwheel --output-dir wheelhouse
