env:
  global:
  - CIBW_TEST_REQUIRES="nose2"
  - CIBW_TEST_COMMAND="cd {project}/tests && nose2"
  - CIBW_SKIP="cp27-*"
  - TWINE_USERNAME=mikedh
  - secure: RwiL3Q+SoQ/Ju6NXVXJK/BoeLZrb2gCdmvki1FNvWo1N+SiR6TAG4fGWOZ6zwi9yKoHqOxY9pTA/gd8JRWK8zH/80xh7LBztkTLNnB0ge/KCEzz4QVW925JQCy38v/F6DQQ3Tfb771jQYFKgIvPuOALd5THklc3DNdanX9erVJWb1jcrCT6G5OkYyyAvqejNRymVnA/lF9cAtnKlXxu19ywggj9BHprmITWl+iYUmYTPrrurNAvOs3l2IShWD2LeSRup9ghuL/CkjRGzhJ6ueZlFOHOANrt/eJ6pcWIk6eBr86cxWmPi9hQGnU2PwUq1lIi7fONVQ/c2MJkJF4U8IJ096eq4AXiYBopynTlt0C311WPcP5fyOEYvsrDCq7NH/i3FD5oXsV0qr5zhdYWAtbuxYj/vIxS38lYVu8jNrcH3/KMN7gk353bouNc61yl/3E3uOjNhcmUI5RE6E/VIOacGoOkdeiKApqVXO/koLrXvn3jDEH8u3SpoAl0ksfTnJyHAc/z349Fa67JFJVWZXjKmdKHJFLTMuluUaQfZVFKjp0C1TUvyJioYVHiYtWEED/mGQmzrdVpMjmcU3vKLm8TuODoCbUBiG1bADPMgNrmH5e79ockSp9X97QqsuYavWw1FVu/M8/PH10p60gr/BVcvyH3mH1lS1wyn3sqSRJU=
  - secure: AiR9f9+E3NbbCvtX651NxkNnXRyKpdGn50VJ5RReawAnYjj+0TCfqAkQcD5D9wq2tQVQwarhH649GRvT5dYGJZTusOam6f2zOKJfx8W8LiSKUMwFA6yk5vhNIU08ViU7WfYs1oNM3brfNSET67dZarmRCDJrIFqQ6/COOqc19S+aDWF/06IMg+l80FEoWb2oQN4qCTSus+G5XnmFWjTP02/3M0/lpIFI3YG13fAdnmu5tGCoyEIW0QZbiibQQX1v2Pt4Gwons2e+s5Zu6OEihxgQp3ym5+Ru+dWpXhtmuTRvMBYqIdHd4yfKfV3ZjC3WiXxAdjuZXEo0bqF9nARAcDQnA8wCkucXye4KWj29MLFpVnFBivyYFVQD0bBqAltnCwSXhH+gpbpsA9RMilUYCUJtvXRlviEKRRwP/vKYck8ukEnTYUtIOuSrcGGCnl7GxkUcOp20/lr1wUd3wJq4iPCl8i7Lrh+T3tzui5VmdEewGs5Ng+P7Obt9eYpD/uFNIEzbomkSWmnD46ngao9yC0m3DP2yjQlvyGN7Cz4/iq1VYq9arjRC7FgRGzG7oo+RQxtaue9EO39mvOgH3Giuu9o6ANsCS94WhPvnwVYA5+bhPc4hJSqrJgMvkkDSu8Xcyb9SvkMjxqiHMRSdNnlXn4WQ8yYhDol89z1PFwBVewc=
matrix:
  include:
  - dist: trusty
    sudo: required
    language: python
    python: '3.6'
    services:
    - docker
install:
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew install python3; fi
- pip3 install cibuildwheel
script:
- pip install cibuildwheel==0.9.2
- cibuildwheel --output-dir wheelhouse
- python -m pip install twine
- python -m twine upload wheelhouse/*.whl
