env:
  global:
  - CIBW_TEST_REQUIRES="nose2"
  - CIBW_TEST_COMMAND="cd {project}/tests && nose2"
  - CIBW_SKIP="cp27-*"
  - TWINE_USERNAME=mikedh
  - secure: Zp1SU/HtK9V6Tahoz4M26iTHaCxUxUjAgjkqySZcp8s93kHP7MCcEIJoZgp6q5bgZRucT98kSDAD/9UAzJUnmucj6ZKV+req7X06uJrw+WLtedwv1/3jGtjC3NdiloGeqIva/nJ+3s5sDBLntw0D8bUrpzVRku9qqFeeO1hrBpSi+5nW2aIfCA5XOACoY3y//U1vEyncar76nY3Bj5aX0yCr2OcxPFsZpQGuWyo8Ctufy6gM/TBpWtv+cVygHyr4wiWyP1NWl3nTcaii1oMaqlXKIexN98a0/dXTGAA95IMrYPdA1vjIi+iwEQUetavqouZiJOdmyMu/qpQTZEF+c9LrQKNat7EnE9VkeJLLdBbZ8vFBDdEgMgydYAYfrphRrWQQ8RHAp/jnoFzwYB17iHgOe+QtKjYdpfBwBQAjsj1+ZNMD+J1Sei5ys1apFh1IorS8kZzKKeOQDYboAQrHU8yxEJiZGg3SV0OjQoxo0g7Uft6Smh/MpkeIeyn503X1c9xay3eqx2qsyo0LHVP4XO5b02mCbUEmz1ML+Es1wi+KFB/mt1gNqKj9uZvRhyIa2Y6xFKucfGJKH8pHi4PI+6teSh04HdPTTHl3leM9KkA807WbqLcJXblhZRTADzSdWlTOjyqBzY60DpgWGH4tYh35ShDaqx68uU5HK2Bhg5c=
matrix:
  include:
  - dist: trusty
    sudo: required
    language: python
    python: '3.6'
    services:
    - docker
install:
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew install python3; fi
- pip3 install cibuildwheel
script:
- pip install cibuildwheel==0.9.2
- cibuildwheel --output-dir wheelhouse
- python -m pip install twine
- python -m twine upload wheelhouse/*.whl
